export const aboutDelphiAndHowItWorks = [
  {
    title: "How does The Delphi Oracle work?",
    content: [
      "Think of The Delphi Oracle as your AI-powered astrology guide for self-discovery.. We blend AI-powered astrology with human expertise to deliver fully customized birth chart insights and relationship compatibility readings—all tailored to your unique birth details.",
      "",
      "",
      "💫 Ask anything! Whether you're looking for deep insights into your life purpose, love life, career, friendships, or health - or have a completely unique question - The Oracle is here for you.",
      "",
      "",
      "✨ Your profile setup gives you a FREE personalized astrology reading and 3 credits to explore!",
      "",
      "",
      "Once your profile is set up, you can ask questions freely or explore readings in categories like:",
      "",
      "🌟 Know Thyself - Dive into your birth chart & personal strengths.",
      "",
      "💖 Love Realm - Crushes, soulmates, and relationship clarity.",
      "",
      "💼 Career & Finances - Discover your ideal career path & financial alignment.",
      "",
      "🌿 Health & Wellbeing - Understand your mind-body-energy connection.",
      "",
      "🌍 Social Sphere - Explore friendships, networking, and compatibility.",
      "",
      "",
      "💡 Need a full walkthrough? Head to our How It Works page for a step-by-step guide on navigating The Delphi Oracle.",
    ],
  },
  {
    title: "What types of readings can I access?",
    content: [
      "We cover all the big (and small) life questions with AI-powered astrology insights.",
      "",
      "",
      "✨ Individual Readings → Get insights on personal growth, love, career, and wellbeing.",
      "",
      "💞 Synastry Readings → Explore compatibility in Romance, Friendship, and Business.",
      "",
      "🌟 Daily Cosmic Whispers → Personalized messages, straight from the stars.",
      "",
      "❓ Ask Anything → No limits—your question, your way.",
      "",
      "",
      "💫 Sign up now to unlock extra free credits and start exploring your personal astrology insights!",
    ],
  },
  {
    title: "What is synastry?",
    content: [
      "Synastry = Astrology's Ultimate Compatibility Test!",
      "",
      "",
      "Synastry, also known as relationship astrology, compares two birth charts to reveal how your energies align in love, friendship, or business.",
      "",
      "",
      "✨ Find out:",
      "",
      "✔ Your connection's strengths & challenges",
      "",
      "✔ How to grow & align with someone",
      "",
      "✔ Whether you're cosmically compatible",
      "",
      "",
      "Use synastry readings to understand your soulmate, bestie, or business partner.",
    ],
  },
  {
    title: "Can I ask about the future?",
    content: [
      "We don't predict the future, but we help you navigate it!",
      "",
      "",
      "While we don't offer detailed future predictions, our astrology insights help you:",
      "",
      "✨ Understand your birth chart and life patterns",
      "",
      "🌙 Track current planetary influences and how they affect you",
      "",
      "🚀 Spot upcoming opportunities based on cosmic alignments",
      "",
      "",
      "Big news: We're working on adding more predictive features—stay tuned! Your support helps shape what's next.",
    ],
  },
  {
    title: "Can I use The Delphi Oracle without signing up?",
    content: [
      "✨ Yep! Your profile setup gives you a FREE personalized astrology reading and 3 credits to explore—no account needed.",
      "",
      "",
      "Try it out and see how The Oracle works its magic for you!",
      "",
      "",
      "💫 Want more? Sign up to:",
      "",
      "✔ Get extra free credits for more astrology readings",
      "",
      "✔ Access synastry compatibility insights",
      "",
      "✔ Save & revisit your personal astrology insights anytime",
    ],
  },
  {
    title: "How is The Delphi Oracle different from other astrology platforms?",
    content: [
      "We blend AI-powered astrology with human expertise to bring you deeply personalized insights like no other. Here's what makes us unique:",
      "",
      "",
      "✔ Custom response styles - Choose from deep astrology, a mix, or everyday language.",
      "",
      "✔ Human-crafted accuracy - AI-powered insights, guided by human expertise, ensure precision and authenticity.",
      "",
      "✔ Flexible credits system - Pay for what you use—no subscriptions, no fluff.",
      "",
      "✔ Next-level compatibility readings - Explore synastry in love, friendship, and business.",
      "",
      "✔ Ask Anything, Anytime - Unlike other astrology platforms, you're not limited to pre-set categories—ask whatever's on your mind!",
    ],
  },
  {
    title: "How accurate are the astrology readings?",
    content: [
      "Our insights are based on precise astrological calculations combined with human expertise, ensuring a balance of depth and clarity.",
      "",
      "",
      "✨ But here's the thing: Astrology is a guidance tool, not a fixed fate. Your free will and personal choices shape your journey—The Oracle simply helps you navigate it with wisdom.",
    ],
  },
];

export const creditsAndReferral = [
  {
    title: "How accurate are the astrology readings?",
    content: [
      "How do I get credits, and what are my top-up options?",
      "",
      "",
      "You start with free credits and can earn more in two ways:",
      "",
      "",
      "💫 Refer friends - Invite others and get bonus credits.",
      "",
      "💰 Purchase affordable credit packages - Choose from options like Starlight Starter or Galactic Sage to get more insights whenever you need them.",
    ],
  },
  {
    title: "How does the Referral Program work?",
    content: [
      "Go to Profile > Settings to find your unique referral code. You can customize it and easily share it with friends.",
      "",
      "",
      "💫 Invite Your Friends & Get Free Credits!",
      "",
      "✔ Earn 5 credits for every friend who signs up using your code.",
      "",
      "✔ Your friend gets 3 free credits—it's a win-win!",
      "",
      "✔ More friends = more credits = more cosmic insights.",
    ],
  },
  {
    title: "How do I use the referral code COSMICSTART?",
    content: [
      "If you're new to The Delphi Oracle, enter COSMICSTART during sign-up to receive bonus credits—it's that easy!",
    ],
  },
];

export const personalizationAndFeatures = [
  {
    title: "How do I choose my preferred response style?",
    content: [
      "During setup, you can select from three response styles to match your astrology fluency:",
      "",
      "",
      "🔹 Astrological Expert Level - Deep, technical astrology terminology.",
      "",
      "🔹 Moderate Astrology + Daily Language - A mix of astrology terms and everyday language.",
      "",
      "🔹 Simple Daily Language - Clear, easy-to-understand answers without astrology jargon.",
    ],
  },
  {
    title: "Can I change my birth details after signing up?",
    content: [
      "Your birth details generate your unique astrology insights and can't be changed after setup.",
      "",
      "",
      "💡 Made a mistake? Contact our Support Team at support@thedelphioracle.com for assistance.",
    ],
  },
  {
    title: "Can I save or revisit my readings?",
    content: [
      "Save and revisit your AI-powered astrology insights anytime with our PDF export feature.",
      "",
      "",
      "💫 You can also download and share your Synastry readings—because self-discovery is even more powerful when explored together.",
    ],
  },
  {
    title: "What happens to unused credits?",
    content: [
      "Unused credits never expire - they stay in your account so you can continue your journey whenever you're ready.",
    ],
  },
  {
    title: "How do I change the language of my response?",
    content: [
      "Want your insights in a different language? Just specify your preferred language when asking your question.",
      "",
      "",
      '💬 Example: "What habits will best support me to achieve my highest potential? Write this in French."',
    ],
  },
];

export const accessingAndEngaging = [
  {
    title: "How do I use The Delphi Oracle on my phone?",
    content: [
      "🌟 No app? No problem! Until our mobile app launches:",
      "",
      "✔ Pin the website to your home screen for quick access.",
      "",
      "✔ Bookmark it in your browser for quick navigation.",
      "",
      "✔ Follow us on Instagram & TikTok for exclusive updates on our launch.",
      "",
    ],
  },
  {
    title: "Will there be an app in the future?",
    content: [
      "🚀 Yes! The Delphi Oracle app is coming! We're building a seamless mobile experience to make astrology insights even more accessible.",
      "",
      "",
      "💫 Stay tuned—the stars are aligning for something big!",
    ],
  },
  {
    title: "How Can I Connect with the Delphi Oracle Community?",
    content: [
      "✨ Connect with the Delphi Oracle Community—because self-discovery is even better together!",
      "",
      "",
      "🔮 Instagram - @the.delphioracle",
      "",
      "🎥 TikTok - @thedelphioracle",
      "",
      "✖ X (Twitter) - @urdelphioracle",
      "",
      "🧵 Threads - @the.delphioracle",
      "",
      "📘 Facebook - The Delphi Oracle",
      "",
      "▶ YouTube - @thedelphioracle",
      "",
      "",
      "💫 Be part of a global movement exploring astrology, self-discovery, and the universe within.",
      "",
      "",
      "Your journey with The Delphi Oracle is unique, and we'd love to hear about it!",
      "",
      "",
      "🌟 Share your experience using #TheDelphiOracle or tag/mention us directly for a chance to be featured on our Instagram, TikTok, or website. Whether it’s a magical insight, a surprising reading, or your thoughts on self-discovery, we want to celebrate your cosmic journey with you!",
    ],
  },
];

export const privacyAndSupport = [
  {
    title: "Is my information secure on The Delphi Oracle?",
    content: [
      "Yes! Your privacy is our priority. All data is confidential, never shared, and used only for your private astrology readings. Our system is built with strong security measures to protect your information.",
    ],
  },
  {
    title: "Having technical issues? Try this first.",
    content: [
      "✔ Refresh the page and re-enter your question.",
      "",
      "✔ Check your internet connection for stability.",
      "",
      "✔ Clear your browser cache if responses seem slow.",
      "",
      "",
      "Still need help? Contact support@thedelphioracle.com—we're happy to help!",
    ],
  },
  {
    title: "Can I get a refund for purchased credits?",
    content: [
      "All credit purchases are final, but if a technical issue affects your purchase, reach out to support@thedelphioracle.com—we'll be happy to assist.",
    ],
  },
  {
    title: "How can I ask questions to get the best answers?",
    content: [
      "💡 Pro Tip: The better the question, the better the insight. Ask the oracle specific questions for the clearest guidance!",
      "",
      "",
      "❌ Instead of: 'What's in store for me?'",
      "",
      "✅ Try: 'Which career path best aligns with my birth chart?'",
    ],
  },
  {
    title: "How can I delete my account?",
    content: [
      "⚠ If you want to delete your account permanently:",
      "",
      "1. Go to Profile > Settings",
      "",
      "2. Select Delete Account",
      "",
      "",
      "🚨 This action cannot be undone and will remove all your data from The Delphi Oracle.",
    ],
  },
  {
    title: "How can I contact support?",
    content: [
      "For any questions, technical issues, or feedback, email support@thedelphioracle.com.",
      "",
      "",
      "💫 We're here to make your experience smooth and magical!",
    ],
  },
];

export const rewardsAndGrowing = [
  {
    title: "Earn Free Credits for Social Media Sharing",
    content: [
      "💬 Share your experience with The Delphi Oracle on Instagram, TikTok, Threads, X, Facebook, YouTube, Reddit & more to earn free credits!",
      "",
      "✔ Earn up to 40 credits per post + bonus credits for high engagement.",
      "",
      "✔ Reviews, testimonials & UGC (user-generated content) can also earn extra credits.",
    ],
  },
  {
    title: "Provide Platform Feedback & Testing",
    content: [
      "🛠 Help shape The Delphi Oracle by testing features, submitting feedback, and joining discussions.",
      "",
      "✔ Earn credits for testing new features & providing valuable insights.",
    ],
  },
  {
    title: "Become an Affiliate & Earn Commissions",
    content: [
      "💰 Want to monetize your influence? Join as an affiliate, ambassador, or influencer and earn commissions on every astrology credit purchase you drive.",
      "",
      "✔ Up to 50% commission based on performance.",
      "",
      "✔ Exclusive perks for top contributors & brand ambassadors!",
      "",
      "",
      "📩 Want in? Apply by emailing marketing@thedelphioracle.com and start contributing today!",
    ],
  },
];
